"""add_timetable_entries

Revision ID: 0554690a139f
Revises: 3ec445729e79
Create Date: 2026-06-08 22:02:37.665478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0554690a139f'
down_revision: Union[str, Sequence[str], None] = '3ec445729e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('period_index', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'day_index', 'period_index', name='uq_timetable_entry_slot')
    )
    op.create_index(op.f('ix_timetable_entries_id'), 'timetable_entries', ['id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_school_id'), 'timetable_entries', ['school_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_section_id'), 'timetable_entries', ['section_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_subject_id'), 'timetable_entries', ['subject_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_teacher_id'), 'timetable_entries', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_entries_teacher_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_subject_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_section_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_school_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_id'), table_name='timetable_entries')
    op.drop_table('timetable_entries')
    # ### end Alembic commands ###
