"""add_schools_and_teacher_class_mappings

Revision ID: 3ec445729e79
Revises: dce2c8d7ad70
Create Date: 2026-06-07 23:07:32.558444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec445729e79'
down_revision: Union[str, Sequence[str], None] = 'dce2c8d7ad70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create the schools and teacher_class_mappings tables
    op.create_table(
        'schools',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('address', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.create_index(op.f('ix_schools_name'), 'schools', ['name'], unique=True)

    op.create_table(
        'teacher_class_mappings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('teacher_id', sa.Integer(), nullable=False),
        sa.Column('class_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('teacher_id', 'class_id', name='uq_tcm_teacher_class'),
    )
    op.create_index(op.f('ix_teacher_class_mappings_class_id'), 'teacher_class_mappings', ['class_id'], unique=False)
    op.create_index(op.f('ix_teacher_class_mappings_id'), 'teacher_class_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_class_mappings_teacher_id'), 'teacher_class_mappings', ['teacher_id'], unique=False)

    # 2. Add school_id as NULLABLE first so existing rows don't violate NOT NULL
    op.add_column('school_classes', sa.Column('school_id', sa.Integer(), nullable=True))
    op.add_column('teachers', sa.Column('school_id', sa.Integer(), nullable=True))

    # 3. Insert a default school to absorb any pre-existing data
    conn = op.get_bind()
    result = conn.execute(
        sa.text("INSERT INTO schools (name) VALUES ('Default School') RETURNING id")
    )
    default_school_id = result.fetchone()[0]

    # 4. Backfill existing rows with the default school id
    conn.execute(
        sa.text("UPDATE school_classes SET school_id = :sid WHERE school_id IS NULL"),
        {"sid": default_school_id},
    )
    conn.execute(
        sa.text("UPDATE teachers SET school_id = :sid WHERE school_id IS NULL"),
        {"sid": default_school_id},
    )

    # 5. Now make the columns NOT NULL
    op.alter_column('school_classes', 'school_id', nullable=False)
    op.alter_column('teachers', 'school_id', nullable=False)

    # 6. Update index / constraints on school_classes
    op.drop_index(op.f('ix_school_classes_name'), table_name='school_classes')
    op.create_index(op.f('ix_school_classes_name'), 'school_classes', ['name'], unique=False)
    op.create_index(op.f('ix_school_classes_school_id'), 'school_classes', ['school_id'], unique=False)
    op.create_unique_constraint('uq_school_class_school_name', 'school_classes', ['school_id', 'name'])
    op.create_foreign_key(None, 'school_classes', 'schools', ['school_id'], ['id'], ondelete='CASCADE')

    # 7. Index and FK on teachers
    op.create_index(op.f('ix_teachers_school_id'), 'teachers', ['school_id'], unique=False)
    op.create_foreign_key(None, 'teachers', 'schools', ['school_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_index(op.f('ix_teachers_school_id'), table_name='teachers')
    op.drop_column('teachers', 'school_id')
    op.drop_constraint(None, 'school_classes', type_='foreignkey')
    op.drop_constraint('uq_school_class_school_name', 'school_classes', type_='unique')
    op.drop_index(op.f('ix_school_classes_school_id'), table_name='school_classes')
    op.drop_index(op.f('ix_school_classes_name'), table_name='school_classes')
    op.create_index(op.f('ix_school_classes_name'), 'school_classes', ['name'], unique=True)
    op.drop_column('school_classes', 'school_id')
    op.drop_index(op.f('ix_teacher_class_mappings_teacher_id'), table_name='teacher_class_mappings')
    op.drop_index(op.f('ix_teacher_class_mappings_id'), table_name='teacher_class_mappings')
    op.drop_index(op.f('ix_teacher_class_mappings_class_id'), table_name='teacher_class_mappings')
    op.drop_table('teacher_class_mappings')
    op.drop_index(op.f('ix_schools_name'), table_name='schools')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_table('schools')
    # ### end Alembic commands ###
