"""initial_data_layer

Revision ID: dce2c8d7ad70
Revises: c4b1b64b3720
Create Date: 2026-06-07 16:36:41.668736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce2c8d7ad70'
down_revision: Union[str, Sequence[str], None] = 'c4b1b64b3720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_classes_id'), 'school_classes', ['id'], unique=False)
    op.create_index(op.f('ix_school_classes_name'), 'school_classes', ['name'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=True)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_class_id', 'name', name='uq_section_class_name')
    )
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_index(op.f('ix_sections_school_class_id'), 'sections', ['school_class_id'], unique=False)
    op.create_table('subject_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('periods_per_week', sa.Integer(), nullable=False),
    sa.CheckConstraint('periods_per_week >= 1', name='ck_requirement_periods_positive'),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_class_id', 'subject_id', name='uq_requirement_class_subject')
    )
    op.create_index(op.f('ix_subject_requirements_id'), 'subject_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_subject_requirements_school_class_id'), 'subject_requirements', ['school_class_id'], unique=False)
    op.create_index(op.f('ix_subject_requirements_subject_id'), 'subject_requirements', ['subject_id'], unique=False)
    op.create_table('teacher_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('periods_per_week', sa.Integer(), nullable=False),
    sa.CheckConstraint('periods_per_week >= 1', name='ck_allocation_periods_positive'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'section_id', 'subject_id', name='uq_allocation_teacher_section_subject')
    )
    op.create_index(op.f('ix_teacher_allocations_id'), 'teacher_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_allocations_section_id'), 'teacher_allocations', ['section_id'], unique=False)
    op.create_index(op.f('ix_teacher_allocations_subject_id'), 'teacher_allocations', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_allocations_teacher_id'), 'teacher_allocations', ['teacher_id'], unique=False)
    op.add_column('teachers', sa.Column('email', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_unique_constraint(None, 'teachers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_column('teachers', 'email')
    op.drop_index(op.f('ix_teacher_allocations_teacher_id'), table_name='teacher_allocations')
    op.drop_index(op.f('ix_teacher_allocations_subject_id'), table_name='teacher_allocations')
    op.drop_index(op.f('ix_teacher_allocations_section_id'), table_name='teacher_allocations')
    op.drop_index(op.f('ix_teacher_allocations_id'), table_name='teacher_allocations')
    op.drop_table('teacher_allocations')
    op.drop_index(op.f('ix_subject_requirements_subject_id'), table_name='subject_requirements')
    op.drop_index(op.f('ix_subject_requirements_school_class_id'), table_name='subject_requirements')
    op.drop_index(op.f('ix_subject_requirements_id'), table_name='subject_requirements')
    op.drop_table('subject_requirements')
    op.drop_index(op.f('ix_sections_school_class_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_school_classes_name'), table_name='school_classes')
    op.drop_index(op.f('ix_school_classes_id'), table_name='school_classes')
    op.drop_table('school_classes')
    # ### end Alembic commands ###
